/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
    export interface GlobalComponents {
        Button: typeof import("primevue/button")["default"];
        InputText: typeof import("primevue/inputtext")["default"];
        FloatLabel: typeof import("primevue/floatlabel")["default"];
        DataTable : typeof import("primevue/datatable")["default"];
        Column: typeof import("primevue/column")["default"];
        ColumnGroup: typeof import("primevue/columngroup")["default"];
        Row: typeof import("primevue/row")["default"];
    }
}
